### ISSUE TITLE
회원가입 기능 구현

### ISSUE THREAD

**Issue by uije91** [uije91/CustomBoard#1]
## 💡 Feature Issue
회원 가입 기능을 구현합니다.

## 🌿  To-do
- [x] 모든 사용자는 회원가입을 할 수 있으며 일반 회원으로 가입됩니다.
- [x] 일반회원, 관리자 2개의 권한이 있으며, 별도의 관리자 회원가입 API는 제공하지 않습니다.
- [x] 이메일, 닉네임, 패스워드, 휴대폰번호를 입력 받습니다.
