### ISSUE TITLE
이메일 인증 구현

### ISSUE THREAD

**Issue by uije91** [uije91/CustomBoard#2]
## 💡 Feature Issue
이메일 인증 기능을 구현합니다.

## 🌿  To-do
- [x] 이메일 인증을 하면 6자리의 코드가 이메일로 전송됩니다.
- [x] 코드는 redis에 저장합니다. 
- [x] 이메일 인증을 통한 코드가 일치하면 true, 아니면 false를 반환합니다.
