### ISSUE TITLE
회원 기능 구현

### ISSUE THREAD

**Issue by uije91** [uije91/CustomBoard#5]
## 💡 Feature Issue
회원 서비스 개발

## 🌿  To-do
- [x] 회원 정보 조회 : 이메일, 닉네임, 휴대폰 번호를 조회합니다.
- [x] 회원 정보 수정 : 닉네임, 패스워드, 휴대폰 번호를 수정합니다.
- [x] 회원 탈퇴 : 회원 탈퇴시 상태가 RESIGN으로 변경되며, 30일 후 완전히 탈퇴합니다.
- [x] 비밀번호 찾기 : 이메일 인증 후 비밀번호를 재설정합니다.
